### ISSUE TITLE
error when inject

### ISSUE THREAD

**Issue by Teruhashi12** [Z4ee/StarRail-ACE-B#1]
![red](https://user-images.githubusercontent.com/90950171/235138238-a676475c-974a-46f3-98b0-ef6bb3ee3aec.PNG)

**Comment by Z4ee** [comment]
![image](https://user-images.githubusercontent.com/113752393/235138850-8cb81698-a82a-4d50-88ad-9ab8a45ab45d.png)

after that, you should start the game

**Comment by Teruhashi12** [comment]
> ![image](https://user-images.githubusercontent.com/113752393/235138850-8cb81698-a82a-4d50-88ad-9ab8a45ab45d.png)
> 
> after that, you should start the game

got this error
![res](https://user-images.githubusercontent.com/90950171/235140446-4598399a-b0f7-4a94-b137-756212d95f85.PNG)

**Comment by Teruhashi12** [comment]
> do it like in this video: https://youtu.be/pIr6wQtz4kw
> 
> if the error remains then I will have to make launcher for bypass |:

im very sorry,its got the error because i use the old minhook lib..the problem is solved when i build with new lib minhook..thanks for the response

**Comment by Suntz246** [comment]
I'm in trouble, too
console log:
Unsupported SRB version -> 0xC3CCCE413D8A877B Failed to init bypass

**Comment by Z4ee** [comment]
> I'm in trouble, too console log: Unsupported SRB version -> 0xC3CCCE413D8A877B Failed to init bypass

do you have the chinese version of the game?
send your StarRailBase.dll
