### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by Endless-index** [Z4ee/StarRail-ACE-B#14]
![image](https://github.com/Z4ee/StarRail-ACE-B/assets/84027024/b3609df1-b030-495b-9c74-24d46582aa4b)

**Comment by Z4ee** [comment]
looks like your game opens too fast

**Comment by Togetogean** [comment]
Try check your startup apps setting then disable anything related to Star Rail.
If your game opens too fast, try to lower the resolution and not fullscreen the game first.

**Comment by Endless-index** [comment]
I try HSR-Launcher to Hook this game,but it work,
