### ISSUE TITLE
Unsupported SRB version -> 0xC3CCCE413D8A877B Failed to init bypass

### ISSUE THREAD

**Issue by Suntz246** [Z4ee/StarRail-ACE-B#2]
I downloaded the dll for release v2 directly and injected using Extreme.Injector.v3.7.3 according to the video

**Comment by Suntz246** [comment]
> 你有中文版的游戏吗？ 发送您的 StarRailBase.dll

https://drive.google.com/file/d/1zoFO700zN1hBhKKaiAZsodqKTrOKm__X/view?usp=share_link

**Comment by Z4ee** [comment]
recompile new source or download new dll from releases

i added support your version of the game

**Comment by Suntz246** [comment]
> > 重新编译新源代码或从发布版本下载新的dll
> > 我添加了对您的游戏版的支持
> 
> 不受支持的 SRB 版本 -> 0x7560DA00 无法初始化旁路

Is it the same question?

**Comment by Suntz246** [comment]
> > > 重新编译新源代码或从发布版本下载新的dll
> > > 我添加了对您的游戏版的支持
> > 
> > 
> > 不受支持的 SRB 版本 -> 0x7560DA00 无法初始化旁路
> 
> Is it the same question?

![1111](https://user-images.githubusercontent.com/49502214/235158939-d79fd1bc-9f47-41b2-96ab-2b15019ecdee.png)

**Comment by Z4ee** [comment]
> > 重新编译新源代码或从发行版下载新的 dll
> > 我添加了对您的游戏版本的支持
> 
> Unsupported SRB version -> 0x7560DA00 Failed to init bypass
try this dll:
https://dropmefiles.com/mTzZc

**Comment by Suntz246** [comment]
> > > 重新编译新源代码或者从发行版下载新的dll
> > > 我添加了对您的游戏版的支持
> > 
> > 
> > 不受支持的 SRB 版本 -> 0x7560DA00 无法初始化旁路
> 
> 试试这个 dll： https: [//dropmefiles.com/mTzZc](https://dropmefiles.com/mTzZc)

That's all right, thank you
