### ISSUE TITLE
build Error

### ISSUE THREAD

**Issue by azubu23202869** [Z4ee/StarRail-ACE-B#3]
![image](https://user-images.githubusercontent.com/43975713/235159665-73f541dc-d7f8-4eda-911c-ad3db0b1267c.png)

**Comment by Z4ee** [comment]
you must include the minhook library to compile without errors

**Comment by azubu23202869** [comment]
![image](https://user-images.githubusercontent.com/43975713/235162120-3d2a5229-5b80-425f-bfe4-08a4d4c472b7.png)

**Comment by Z4ee** [comment]
try compiling the source code which is now on github

I have added already compiled minhook library

**Comment by azubu23202869** [comment]
![image](https://user-images.githubusercontent.com/43975713/235167530-e99d686d-f652-4ea5-b627-e55495fd13b6.png)

![image](https://user-images.githubusercontent.com/43975713/235167692-f370c616-3e0c-4753-8677-d71d910a70af.png)

![image](https://user-images.githubusercontent.com/43975713/235167139-29ea7580-c631-473b-bc7a-56a2eab7b5ed.png)

**Comment by azubu23202869** [comment]
![image](https://user-images.githubusercontent.com/43975713/235168633-d1ccf1cb-3e22-4043-b29c-6fc9e54d3c1e.png)

Oh my god, I forgot to check the option for automatic injection. Sorry about that, thank you very much.

**Comment by electrocome** [comment]
Cheat Engine changes the number of items to 99.

When using items inscription not enough items.

on the screen 99 ?

What can I change in Cheat Engine

**Comment by linosick** [comment]
> [electrocome](/electrocome)

same
