### ISSUE TITLE
How can dlls be manually injected into starrail.exe?

### ISSUE THREAD

**Issue by yyxcodeqaz** [Z4ee/StarRail-ACE-B#4]
#Injection error
1.After compilation, it is star_ Rail.dll, how should I add star_ Inject rail.dll into starrail.exe?
2.If an injector is used, it will report an error indicating that memory cannot be allocated during injection.

**Comment by Z4ee** [comment]
use extreme injector with auto inject option:
https://youtu.be/pIr6wQtz4kw

**Comment by yyxcodeqaz** [comment]
Thanks, my problem has been resolved
