### ISSUE TITLE
unresolved external

### ISSUE THREAD

**Issue by Togetogean** [Z4ee/StarRail-ACE-B#5]
![image](https://user-images.githubusercontent.com/37516051/235326135-1fb26d4e-d205-4574-bbe8-66a18449164d.png)
just downloaded the zip and try to build it. and this happen.

**Comment by Z4ee** [comment]
what version of visual studio are you using?

**Comment by Togetogean** [comment]
I'm using

**Comment by Togetogean** [comment]
i'm using vs 2022
but it resolved when i changed it from debug to release when building.

Thanks
