### ISSUE TITLE
Injuection Failed

### ISSUE THREAD

**Issue by ShiningorDying** [Z4ee/StarRail-ACE-B#8]
Injuection Failed, but dont know why
<img width="357" alt="屏幕截图 2023-05-02 154539" src="https://user-images.githubusercontent.com/85548197/235612653-7dc45249-60a7-4d60-b94e-fce26df75a57.png">

### injuector:
Extreme Injector v3.7.3
Inject object: StarRail.exe
config changes:

- start in secure mode
- scrambling option: extreme
- and nothing more

### Process to the dll:
open star_rail.vcxproj with VS and bulid

> _(btw: i do meet the same problem as@mintygingy
> ![235381502-664920fe-cf13-4e2e-bbd9-c4ba6d46914f](https://user-images.githubusercontent.com/85548197/235614271-0ab06ade-c26e-48a8-b8ce-46fabc1fe13b.png)
> and solved with @Togetogean
> "change debug>release then build it.")_

### game version:
 Chinese version

If there are successful implementers who could provide some possible approaches or need additional information regarding why the problem occurs,  greatly appreciate it. @Z4ee

**Comment by Z4ee** [comment]
https://github.com/Z4ee/StarRail-ACE-B/issues/4

**Comment by ShiningorDying** [comment]
> #4
Solved, with appreciation and respect for the repository
