### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Dewappa** [Z4ee/StarRail-ACE-B#9]
![Screenshot (5)](https://user-images.githubusercontent.com/132409256/235802174-10b34d9e-d5a5-48aa-a5b6-dfd9e05557f1.png)
Has this worked?

**Comment by Z4ee** [comment]
judging by the screenshot, you are using the previous version of the cheat, yes, it also works

**Comment by brownvamp** [comment]
im not sure on how to compile, do u have discord? dru#0555

**Comment by Dewappa** [comment]
> 
i did it like in the video
https://youtu.be/pIr6wQtz4kw

**Comment by Dewappa** [comment]
> judging by the screenshot, you are using the previous version of the cheat, yes, it also works

thanks for info
